#
# VS Code Extension for testing API below:
# - https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
# With the above installed, you'll see a "Send Request" button near the
# POST url below. Click it to send the request.
#
# Documentation:
# - https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches/v5/query.md
#

POST https://api.spacexdata.com/v5/launches/query HTTP/1.1
content-type: application/json

{
  "query": {
    "page": 1,
    "limit": 10
  },
  "options": {
    "populate": [
      {
        "path": "cores.core",
        "select": {
          "serial": 1
        }
      },
      {
        "path": "payloads",
        "select": {
          "type": 1
        }
      }
    ],
    "select": [
      "links.patch.small",
      "success",
      "failures.reason",
      "payloads",
      "name",
      "date_utc",
      "cores.core",
      "id"
    ]
  }
}
